### ISSUE TITLE
minor bug in MORE_GTEST_MACROS.hh 

### ISSUE THREAD

**Issue by Matt-Jessee** [wawiesel/Testing123#17]
I think 

#define EXPECTORASSERT_APPROX(a,b,tol)\ 

should be 

#define EXPECTORASSERT_APPROX(name,a,b,tol)\

Currently getting this compile error:

/Users/m8j/codes/Moonraker/src/moonraker/tests/cgal_test.cc:26:37: error: macro "EXPECTORASSERT_APPROX" passed 4 arguments, but takes just 3
   EXPECT_APPROX(0.0, sw.x(), 1.0e-10);

**Comment by wawiesel** [comment]
Can you make branch hotfix-17 with fix?

**Comment by Matt-Jessee** [comment]
yes.

**Comment by Matt-Jessee** [comment]
@wawiesel 

[m8j ~/codes/Testing123]$ git push origin hotfix-17
Username for 'https://github.com': Matt-Jessee
Password for 'https://Matt-Jessee@github.com':
remote: Permission to wawiesel/Testing123.git denied to Matt-Jessee.
fatal: unable to access 'https://github.com/wawiesel/Testing123.git/': The requested URL returned error: 403

**Comment by Matt-Jessee** [comment]
@wawiesel 

Accepted invitation and pushed to branch hotfix-17

**Comment by wawiesel** [comment]
fixed in v0.5.1
